### ISSUE TITLE
The version of blender

### ISSUE THREAD

**Issue by haoZ-920** [aymenmir1/pix2surf#13]
Thanks for you work! I have installed the Blender 2.90.1 but  I run into some trouble when executing the demo:

Blender 2.90.1 (hash 3e85bb34d0d7 built 2020-09-23 08:34:47)
xcb_connection_has_error() returned true
xcb_connection_has_error() returned true
found bundled python: /home/zhaohao/blender/2.90/python
ArgumentParser(prog='blender', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)
['blender', '--background', '--python', 'render.py', '--', '--body_tex', './test_data/images/body_tex/body_tex.jpg', '--body_mesh', './test_data/meshes/shorts/body_0.obj', '--up_tex', './output/up.jpg', '--up_mesh', './test_data/meshes/shorts/upper_0.obj', '--low_mesh', './test_data/meshes/shorts/lower_0.obj', '--low_tex', './output/low.jpg', '--renderfolder', './video']
4
['--body_tex', './test_data/images/body_tex/body_tex.jpg', '--body_mesh', './test_data/meshes/shorts/body_0.obj', '--up_tex', './output/up.jpg', '--up_mesh', './test_data/meshes/shorts/upper_0.obj', '--low_mesh', './test_data/meshes/shorts/lower_0.obj', '--low_tex', './output/low.jpg', '--renderfolder', './video']
./test_data/meshes/shorts/body_0.obj
Traceback (most recent call last):
  File "/home/zhaohao/pix2surf/render.py", line 171, in <module>
    renderer = Renderer()
  File "/home/zhaohao/pix2surf/render.py", line 13, in __init__
    self.setup_scene()
  File "/home/zhaohao/pix2surf/render.py", line 59, in setup_scene
    self.scene.render.alpha_mode = 'TRANSPARENT'
AttributeError: 'RenderSettings' object has no attribute 'alpha_mode'

Blender quit

Could you tell me how to solve it? Thanks again~

**Comment by MotiBaadror** [comment]
Hi @haoZ-920 Try this
`
import os
os.environ["LD_PRELOAD"] = ""

!apt remove libtcmalloc-minimal4
!apt install libtcmalloc-minimal4

os.environ["LD_PRELOAD"] = "/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4.3.0"

!wget https://download.blender.org/release/Blender2.79/blender-2.79-linux-glibc219-x86_64.tar.bz2
!tar -xf blender-2.79-linux-glibc219-x86_64.tar.bz2

# if you still get any errors regarding LD_PRELOAD you can check whether a good path is applied (if the version of library has not changed)
!dpkg -L libtcmalloc-minimal4 

!ln -s /content/blender-2.79-linux-glibc219-x86_64/blender /usr/local/bin/blender
!blender -v
`

**Comment by alexantoniogonzalez2** [comment]
Alternatively, you can download the same version used originally (version 2.79): https://download.blender.org/release/Blender2.79/

That version does not have that error.

**Comment by Void-Mohit** [comment]
**Try to update render.py according to blender version >=2.79**
https://blenderartists.org/t/2-80-cheat-sheet-for-updating-add-ons/1148974

**Comment by chenw191** [comment]
Hi @Void-Mohit , can you generate new garment mesh?

**Comment by Void-Mohit** [comment]
Hi, @chenw191 I am working on it .
